name: Build xformers package

on: [workflow_dispatch]

env:
  XFORMERS_VERSION: 'v0.0.13'

jobs:
  example_matrix:
    strategy:
      matrix:
        CUDA_MAJOR: ['11']
        CUDA_MINOR: ['3']
        CUDA_PATCH:  ['1']
        PYTHON_VERSION: ['3.9', '3.8']

    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3
        with:
          repository: facebookresearch/xformers
          ref: ${{ env.XFORMERS_VERSION }}
          path: xformers
          submodules: 'recursive'

      - run: |
          apt update
          apt install -y wget 
      
      - name: Install cuda-toolkit
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
          dpkg -i cuda-keyring_1.0-1_all.deb
          apt update

      - run: |
          apt install -y cudart-${{ matrix.CUDA_MAJOR}}-${{ matrix.CUDA_MINOR }} cuxxfilt-${{ matrix.CUDA_MAJOR}}-${{ matrix.CUDA_MINOR }} nvcc-${{ matrix.CUDA_MAJOR}}-${{ matrix.CUDA_MINOR }} nvml_dev-${{ matrix.CUDA_MAJOR}}-${{ matrix.CUDA_MINOR }} nvprune-${{ matrix.CUDA_MAJOR}}-${{ matrix.CUDA_MINOR }} nvrtc_dev-${{ matrix.CUDA_MAJOR}}-${{ matrix.CUDA_MINOR }} thrust-${{ matrix.CUDA_MAJOR}}-${{ matrix.CUDA_MINOR }} cublas_dev-${{ matrix.CUDA_MAJOR}}-${{ matrix.CUDA_MINOR }} cufft_dev-${{ matrix.CUDA_MAJOR}}-${{ matrix.CUDA_MINOR }} curand_dev-${{ matrix.CUDA_MAJOR}}-${{ matrix.CUDA_MINOR }} cusolver_dev-${{ matrix.CUDA_MAJOR}}-${{ matrix.CUDA_MINOR }} cusparse_dev-${{ matrix.CUDA_MAJOR}}-${{ matrix.CUDA_MINOR }} npp_dev-${{ matrix.CUDA_MAJOR}}-${{ matrix.CUDA_MINOR }} occupancy_calculator-${{ matrix.CUDA_MAJOR}}-${{ matrix.CUDA_MINOR }}
          
      - uses: actions/setup-python@v4
        id: python
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          cache: 'pip' 
          
      - run: pip install twine ninja torch==1.12.1+cu${{ matrix.CUDA_MAJOR}}${{ matrix.CUDA_MINOR }} torchvision==0.13.1+cu${{ matrix.CUDA_MAJOR}}${{ matrix.CUDA_MINOR }} --extra-index-url https://download.pytorch.org/whl/cu${{ matrix.CUDA_MAJOR}}${{ matrix.CUDA_MINOR }}

      - name: Build 
        working-directory: ./xformers
        env:  
          TORCH_CUDA_ARCH_LIST: "7.0;7.5;8.0;8.6+PTX"
          CUDA_VERSION: ${{ matrix.CUDA_MAJOR}}.${{ matrix.CUDA_MINOR }}
        run: |
          export PATH=/usr/local/cuda-${{ env.CUDA_VERSION }}/bin${PATH:+:${PATH}}
          export LD_LIBRARY_PATH=/usr/local/cuda-${{ env.CUDA_VERSION }}/lib64\${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}
          python ./setup.py bdist_wheel

      - name: Upload package
        working-directory: ./xformers/dist
        env:
          TWINE_REPOSITORY_URL : ${{ secrets.PYPI_CUSTOM_URL }}
          TWINE_USERNAME : ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD : ${{ secrets.PYPI_PASS }}
        run: twine upload --skip-existing --non-interactive ./*.whl

        
      
