name: Build xformers package

on: [workflow_dispatch]

env:
  XFORMERS_VERSION: 'v0.0.13'

jobs:
  example_matrix:
    strategy:
      matrix:
        CUDA_MAJOR: ['11']
        CUDA_MINOR: ['3']
        CUDA_PATCH:  ['1']
        PYTHON_VERSION: ['3.9', '3.8']

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          repository: facebookresearch/xformers
          ref: ${{ env.XFORMERS_VERSION }}
          path: xformers
          submodules: 'recursive'
          
      - uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: '${{ matrix.CUDA_MAJOR}}.${{ matrix.CUDA_MINOR }}.${{ matrix.CUDA_PATCH }}'
          method: 'network'
          sub-packages: '["cudart", "cuxxfilt", "nvcc", "nvml_dev", "nvprune", "nvrtc_dev", "thrust", "cublas_dev", "cufft_dev", "curand_dev", "cusolver_dev", "cusparse_dev", "npp_dev", "occupancy_calculator"]'
        

      - uses: actions/setup-python@v4
        id: python
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          cache: 'pip' 
          
      - run: pip install twine ninja torch==1.12.1+cu${{ matrix.CUDA_MAJOR}}${{ matrix.CUDA_MINOR }} torchvision==0.13.1+cu${{ matrix.CUDA_MAJOR}}${{ matrix.CUDA_MINOR }} --extra-index-url https://download.pytorch.org/whl/cu${{ matrix.CUDA_MAJOR}}${{ matrix.CUDA_MINOR }}

      - name: Build 
        working-directory: ./xformers
        env:  
          TORCH_CUDA_ARCH_LIST: "7.0;7.5;8.0;8.6+PTX"
        run: python ./setup.py bdist_wheel

      - name: Upload package
        working-directory: ./xformers/dist
        env:
          TWINE_REPOSITORY_URL : ${{ secrets.PYPI_CUSTOM_URL }}
          TWINE_USERNAME : ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD : ${{ secrets.PYPI_PASS }}
        run: twine upload --skip-existing --non-interactive ./*.whl

        
      
